# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
Xtr_cpp <- function(x, a, standardization = TRUE, epsilon = 1e-10) {
    .Call('_momentLS_Xtr_cpp', PACKAGE = 'momentLS', x, a, standardization, epsilon)
}

